# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiaEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaentrega',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
