# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MercadoTipo', '__first__'),
        ('Consumidor', '__first__'),
        ('Producto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('totalCompra', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumidor.Consumidor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.Compra')),
                ('mercadoTipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MercadoTipo.MercadoTipo')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
            ],
        ),
    ]
