# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.TextField(max_length=10000, null=True)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('precio', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MercadoTipo_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('mercadoTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoTipo.MercadoTipo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
            ],
        ),
    ]
