# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=1000)),
                ('apellidos', models.CharField(max_length=1000)),
                ('correo', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=1000)),
                ('telefono', models.CharField(max_length=1000)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('extension', models.CharField(max_length=1000)),
                ('usuarioId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
