# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '__first__'),
        ('Productor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='productor',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='nombres',
        ),
        migrations.AddField(
            model_name='productor',
            name='descripcion',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='extension',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productor_producto',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productor.Productor'),
        ),
    ]
