# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20160327_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
