# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productor', '0002_auto_20160308_2217'),
        ('Producto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.FloatField()),
                ('total', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productor.Productor')),
            ],
        ),
    ]
