# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oferta', '0002_auto_20160327_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
